[target.wasm32-unknown-unknown]
rustflags = ["-C", "link-args=-z stack-size=1500000"]

# 64 bit MSVC
[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "link-arg=/STACK:1500000"]

# 64 bit Mingw
[target.x86_64-pc-windows-gnu]
rustflags = ["-C", "link-arg=-Wl,--stack,1500000"]
